### ISSUE TITLE
Question about novelty reward term

### ISSUE THREAD

**Issue by y0ngw00** [arpspoof/Jump#1]
https://github.com/arpspoof/Jump/blob/1c9c1bd5c499e24bab25eb7decaa772b60798794/env/jumper/highjump.py#L184-L199
Hi, I read your paper and got an interest in the reward term.
I could not find the intention of a reward term(on line #191-199) from your paper.
I wonder the role of the term, and what q_bases is(Why the minimum angle difference from root quaternion should be larger than pi/2?)

**Comment by arpspoof** [comment]
q_bases is the quaternion feature of the reference strategies.
pi/2 is just a scaling factor.

Why the minimum angle difference from root quaternion should be larger than pi/2?
There's no 'should'. It can be anything.
We just don't distinguish feature distance of pi/2 or larger and treat them equally good.

**Comment by y0ngw00** [comment]
Thank you
